name: Prerelease

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+-Draft+[0-9]+"


jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Create build/latex/
        run: mkdir -p build/latex/
      - name: Get Version Info
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: "0.0-Draft+1"
      - name: Generate Version Info
        shell: bash
        run: "echo ${{ steps.previoustag.outputs.tag }} > version.txt"
      - name: Prepare latex/version.tex
        shell: bash
        run: printf "\\providecommand*{\\\ruleversion}{" > latex/version.tex
      - name: Extract info from version.txt to latex/version.tex
        shell: bash
        run: grep -E "^([0-9]+)\.([0-9]+)-(Draft|Final)\+[0-9]+(-[a-z0-9]+)?$" version.txt | sed -E 's#^([0-9]+)\.([0-9]+)-(Draft|Final)\+([a-z0-9]+)(-?[a-z0-9]*)$#\1.\2\5\\version\3}#' >> latex/version.tex
      - name: Build Markdown (rules/en.md) to Latex (build/latex/en.tex)
        uses: docker://pandoc/latex:2.14.0.1
        with:
          args: >-
            --from markdown
            --to latex
            --output build/latex/en.tex
            rules/en.md
      - name: Build Markdown (rules/de.md) to Latex (build/latex/de.tex)
        uses: docker://pandoc/latex:2.14.0.1
        with:
          args: >-
            --from markdown
            --to latex
            --output build/latex/de.tex
            rules/de.md
      - name: "Adapt Latex (build/latex/en.tex): Remove ad-hoc label enumeration"
        run: sed -i '/\\def\\labelenumi/d' build/latex/en.tex
      - name: "Adapt Latex (build/latex/de.tex): Remove ad-hoc label enumeration"
        run: sed -i '/\\def\\labelenumi/d' build/latex/de.tex
      - name: "Adapt Latex (build/latex/en.tex): Add {} to terminate \\tightlist"
        run: sed -i 's/\\tightlist/\\tightlist{}/' build/latex/en.tex
      - name: "Adapt Latex (build/latex/de.tex): Add {} to terminate \\tightlist"
        run: sed -i 's/\\tightlist/\\tightlist{}/' build/latex/de.tex
      - name: "Compile Latex (latex/en.tex --> build/latex/en.pdf)"
        uses: xu-cheng/latex-action@v2
        with:
          root_file: latex/en.tex
          latexmk_use_lualatex: true
          args: >-
            -cd-
            -file-line-error
            -halt-on-error
            -interaction=nonstopmode
            -output-directory=build/latex/
      - name: "Compile Latex (latex/de.tex --> build/latex/de.pdf)"
        uses: xu-cheng/latex-action@v2
        with:
          root_file: latex/de.tex
          latexmk_use_lualatex: true
          args: >-
            -cd-
            -file-line-error
            -halt-on-error
            -interaction=nonstopmode
            -output-directory=build/latex/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: build/latex/[ed][ne].pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}